### ISSUE TITLE
Email Service's sendEmail -- please make public

### ISSUE THREAD

**Issue by chadfurman** [clevertech/CleverAuth#11]
We'd like to use the same email sending service to deliver all of our emails.  Being able to access the generic method will be important for this.

**Comment by gimenete** [comment]
Should be available in @clevertech.biz/auth-core@0.0.2 Now any `IEmailService` needs to have a generic `sendEmail()` method. So `DefaultEmailService` implements it. You can use it directly.

New method described here https://github.com/clevertech/CleverAuth/blob/master/core/src/core.ts#L33
