### ISSUE TITLE
Add configuration for email confirmation links

### ISSUE THREAD

**Issue by avesus** [clevertech/CleverAuth#9]
Right now it's hardcoded for `/verify/?emailConfirmationToken=:token`. We need to have URI like `/verify/:token` because React-Router dropped built-in support for search query parameters: https://github.com/ReactTraining/react-router/issues/4410

**Comment by gimenete** [comment]
Well, it's not hardcoded. This is the code:

```javascript
        this.resetPasswordURL +
        '?' +
        querystring.stringify({ emailConfirmationToken })
```

And you define the `resetPasswordURL`. Y can change that to allow to be a function and you would do:

```javascript
resetPasswordURL: (emailConfirmationToken) => `/whatever/${emailConfirmationToken}`
```

**Comment by gimenete** [comment]
Updated package. And by the way published to `@clevertech.biz/auth-core@0.0.1`

Now you can do:

```javascript
new DefaultEmailService({
  projectName: '...',
  emailServiceConfig: { ... },
  confirmEmailURL: (emailConfirmationToken) => `/verify/${emailConfirmationToken}`,
  resetPasswordURL: (emailConfirmationToken) => `/reset/${emailConfirmationToken}`,
  requestResetPasswordURL: '...'
})
```
